version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/"
    schedule:
      interval: "daily"
   
  # factorio-tech/web
 
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/src/FactorioTech.Web/"
    schedule:
      interval: "daily"
  
  # factorio-tech/fbsr-wrapper
  
  - package-ecosystem: "docker"
    directory: "/fbsr-wrapper/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/fbsr-wrapper/deps/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/fbsr-wrapper/"
    schedule:
      interval: "weekly"
