version: '3.8'

volumes:
  factorio:
    external: true
    name: factorio

secrets:
  OAuthProviders__GitHub__ClientId:
    file: ./secrets/OAuthProviders__GitHub__ClientId.secret
  OAuthProviders__GitHub__ClientSecret:
    file: ./secrets/OAuthProviders__GitHub__ClientSecret.secret

services:
  web:
    image: factorio-tech/web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - factorio:/factorio:ro
      - /etc/localtime:/etc/localtime:ro
    secrets:
      - OAuthProviders__GitHub__ClientId
      - OAuthProviders__GitHub__ClientSecret
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Database=postgres;Username=postgres;Password=postgres"
      AppConfig__FactorioDir: "/factorio"
      AppConfig__WorkingDir: "/tmp"
      AppConfig__FbsrWrapperUri: "http://fbsr:8080"
    depends_on:
      - fbsr
      - postgres

  fbsr:
    image: factorio-tech/fbsr-wrapper
    build:
      context: ./fbsr-wrapper
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - factorio:/factorio:ro
      - /etc/localtime:/etc/localtime:ro

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
