apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        - name: default-container-registry
      securityContext:
        fsGroup: 2000
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-web
          image: "{{ .Values.imageNamespace }}/web:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2Gi
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: WEB_URL
              value: https://{{ .Values.hostNames.web }}
            - name: API_URL
              value: https://{{ .Values.hostNames.api }}
            - name: IDENTITY_URL
              value: https://{{ .Values.hostNames.identity }}
            - name: CDN_URL
              value: https://{{ .Values.hostNames.cdn }}
            - name: ENABLE_APPLICATION_INSIGHTS
              value: "true"
            - name: INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: application-insights
                  key: instrumentation_key
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "factorio-tech.fullname" . }}-web
                  key: clientId
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "factorio-tech.fullname" . }}-web
                  key: clientSecret
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
