apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        - name: default-container-registry
      securityContext:
        fsGroup: 2000
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-web
          image: "{{ .Values.imageNamespace }}/web:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: secrets
              mountPath: /mnt/secrets
              readOnly: true
            - name: session
              mountPath: /mnt/session
              readOnly: false
            - name: app-data
              mountPath: /mnt/data
              readOnly: false
            - name: factorio-data
              mountPath: /mnt/factorio
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
      volumes:
        - name: config
          configMap:
            name: {{ include "factorio-tech.fullname" . }}-web
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ include "factorio-tech.fullname" . }}-web
              - secret:
                  name: {{ include "factorio-tech.fullname" . }}-postgres
                  items:
                    - key: connection_string
                      path: ConnectionStrings__Postgres
              - secret:
                  name: application-insights
                  items:
                    - key: instrumentation_key
                      path: ApplicationInsights__InstrumentationKey
        - name: session
          persistentVolumeClaim:
            claimName: {{ include "factorio-tech.fullname" . }}-web-session
        - name: app-data
          azureFile:
            secretName: app-data-share
            shareName: app-data
            readOnly: false
        - name: factorio-data
          azureFile:
            secretName: factorio-data-share
            shareName: factorio-data
            readOnly: true
