apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      imagePullSecrets:
        - name: default-container-registry
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-web
          image: "{{ .Values.imageNamespace }}/web:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: app-data
              mountPath: /data
              readOnly: false
            - name: factorio-data
              mountPath: /factorio
              readOnly: true
          env:
            - name: ConnectionStrings__Postgres
              value: Host=postgres;Database=postgres;Username=postgres;Password=postgres
            - name: AppConfig__FactorioDir
              value: /factorio/Factorio_1.0.0
            - name: AppConfig__WorkingDir
              value: /data
            - name: AppConfig__FbsrWrapperUri
              value: http://fbsr-wrapper
      volumes:
        - name: config
          configMap:
            name: {{ include "factorio-tech.fullname" . }}-web
        - name: app-data
          azureFile:
            secretName: app-data-share
            shareName: app-data
            readOnly: false
        - name: factorio-data
          azureFile:
            secretName: factorio-data-share
            shareName: factorio-data
            readOnly: true
