apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`beta.factorio.tech`)
      kind: Rule
      services:
      - name: {{ include "factorio-tech.fullname" . }}-web
        port: 80
  # tls: # I think this is not required...
  #   certResolver: letsencrypt