apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
data:
  {{- range .Values.oAuthProviders }}
  OAuthProviders__{{ .name }}__ClientId: {{ .clientId | b64enc }}
  OAuthProviders__{{ .name }}__ClientSecret: {{ .clientSecret | b64enc }}
  {{- end }}
