apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "factorio-tech.fullname" . }}-web-session
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
