apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-postgres
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
          resources:
            requests:
              memory: 256Mi
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB_FILE
              value: /var/secrets/database
            - name: POSTGRES_USER_FILE
              value: /var/secrets/username
            - name: POSTGRES_PASSWORD_FILE
              value: /var/secrets/password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: {{ include "factorio-tech.fullname" . }}-postgres-data
              mountPath: /var/lib/pgsql/data
            - name: {{ include "factorio-tech.fullname" . }}-postgres-secrets
              mountPath: /var/secrets
              readOnly: true
      volumes:
          - name: {{ include "factorio-tech.fullname" . }}-postgres-data
            azureDisk:
              kind: Managed
              diskName: {{ .Values.postgres.diskName }}
              diskURI: {{ .Values.postgres.diskURI }}
          - name: {{ include "factorio-tech.fullname" . }}-postgres-secrets
            secret:
              secretName: {{ include "factorio-tech.fullname" . }}-postgres
