apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-pg
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
      - name: {{ include "factorio-tech.fullname" . }}-pg
        image: "{{ .Values.postgres.repository }}:{{ .Values.postgres.tag }}"
        imagePullPolicy: {{ .Values.postgres.pullPolicy }}
        ports:
          - name: postgres
            containerPort: 5432
            protocol: TCP
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER_FILE
            value: /var/secrets/user
          - name: POSTGRES_PASSWORD_FILE
            value: /var/secrets/password
        volumeMounts:
          - name: {{ include "factorio-tech.fullname" . }}-pg-data
            mountPath: /var/lib/pgsql/data
          - name: {{ include "factorio-tech.fullname" . }}-pg-secrets
            mountPath: /var/secrets
            readOnly: true
      volumes:
          - name: {{ include "factorio-tech.fullname" . }}-pg-data
            azureDisk:
              kind: Managed
              diskName: {{ .Values.postgres.diskName }}
              diskURI: {{ .Values.postgres.diskURI }}
          - name: {{ include "factorio-tech.fullname" . }}-pg-secrets
            secret:
              secretName: {{ include "factorio-tech.fullname" . }}-pg
