apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio-tech.fullname" . }}-postgres
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  database: {{ .Values.postgres.database | b64enc }}
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  connection_string: {{ printf "Host=factorio-tech-postgres;Database=%s;Username=%s;Password=%s" .Values.postgres.database .Values.postgres.username .Values.postgres.password | b64enc }}
