apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio-tech.fullname" . }}-pg
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
