apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio-tech.fullname" . }}-postgres
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "factorio-tech.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
