apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factorio-tech.fullname" . }}-fbsr-wrapper
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: fbsr-wrapper
data:
  config.json: |
    {
      "factorio": "/factorio/Factorio_1.0.0"
    }
