apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-fbsr-wrapper
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: fbsr-wrapper
spec:
  replicas: {{ .Values.replicas.fbsrWrapper }}
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: fbsr-wrapper
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: fbsr-wrapper
    spec:
      imagePullSecrets:
        - name: default-container-registry
      securityContext:
        fsGroup: 2000
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-fbsr-wrapper
          image: "{{ .Values.imageNamespace }}/fbsr-wrapper:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: factorio-data
              mountPath: /mnt/factorio
              readOnly: true
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
      volumes:
        - name: config
          configMap:
            name: {{ include "factorio-tech.fullname" . }}-fbsr-wrapper
        - name: factorio-data
          azureFile:
            secretName: factorio-data-share
            shareName: factorio-data
            readOnly: true
