apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-identity
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  replicas: {{ .Values.replicas.identity }}
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: identity
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: identity
    spec:
      imagePullSecrets:
        - name: default-container-registry
      securityContext:
        fsGroup: 2000
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-identity
          image: "{{ .Values.imageNamespace }}/identity:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2Gi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mnt/config
              readOnly: true
            - name: secrets
              mountPath: /mnt/secrets
              readOnly: true
            - name: keys
              mountPath: /mnt/keys
              readOnly: true
            - name: protected
              mountPath: /mnt/protected
              readOnly: false
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
      volumes:
        - name: config
          configMap:
            name: {{ include "factorio-tech.fullname" . }}-identity
        - name: secrets
          projected:
            sources:
              - secret:
                  name: {{ include "factorio-tech.fullname" . }}-identity
              - secret:
                  name: {{ include "factorio-tech.fullname" . }}-postgres
                  items:
                    - key: connection_string
                      path: ConnectionStrings__Postgres
              - secret:
                  name: application-insights
                  items:
                    - key: instrumentation_key
                      path: ApplicationInsights__InstrumentationKey
        - name: keys
          secret:
            secretName: data-protection-certificate
        - name: protected
          persistentVolumeClaim:
            claimName: {{ include "factorio-tech.fullname" . }}-identity-protected
