apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio-tech.fullname" . }}-identity
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
type: Opaque
data:
  OAuthClients__Web__ClientId: {{ .Values.web.clientId | b64enc }}
  OAuthClients__Web__ClientSecret: {{ .Values.web.clientSecret | b64enc }}
  {{- range .Values.identity.providers }}
  OAuthProviders__{{ .name }}__ClientId: {{ .clientId | b64enc }}
  OAuthProviders__{{ .name }}__ClientSecret: {{ .clientSecret | b64enc }}
  {{- end }}
