apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio-tech.fullname" . }}-identity
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "factorio-tech.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: identity
