imageNamespace: ghcr.io/factorio-builds/factorio-build-tech

hostNames:
  web: staging.factorio.tech
  api: api.factorio.tech
  identity: identity.factorio.tech

replicas:
  web: 1
  api: 1
  identity: 1
  fbsrWrapper: 1

postgres:
  image: postgres:13-alpine
  pullPolicy: IfNotPresent
