imageNamespace: ghcr.io/dstockhammer/factorio-tech
hostName: beta.factorio.tech

replicas:
 web: 1
 fbsrWrapper: 1

postgres:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: latest

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
