imageNamespace: ghcr.io/dstockhammer/factorio-tech

replicas:
 web: 1
 fbsrWrapper: 1

postgres:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: latest
  diskName: factorio-tech-postgres
  diskURI: /subscriptions/86a2bd69-00a4-460d-9fda-b2850d41137f/resourceGroups/factorio-tech/providers/Microsoft.Compute/disks/factorio-tech-postgres

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
