apiVersion: v1
kind: Service
metadata:
  name: {{ include "factorio-tech.fullname" . }}-redis
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "factorio-tech.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
