apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-tech.fullname" . }}-rabbitmq
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "factorio-tech.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "factorio-tech.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: {{ include "factorio-tech.fullname" . }}-rabbitmq
          image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: {{ .Values.rabbitmq.pullPolicy }}
          resources:
            requests:
              memory: 256Mi
          ports:
            - name: rabbitmq
              containerPort: 5672
              protocol: TCP
            - name: rabbitmq-mgmt
              containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER_FILE
              value: /var/secrets/username
            - name: RABBITMQ_DEFAULT_PASS_FILE
              value: /var/secrets/password
          volumeMounts:
            - name: {{ include "factorio-tech.fullname" . }}-rabbitmq-secrets
              mountPath: /var/secrets
              readOnly: true
      volumes:
          - name: {{ include "factorio-tech.fullname" . }}-rabbitmq-secrets
            secret:
              secretName: {{ include "factorio-tech.fullname" . }}-rabbitmq
