apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factorio-tech.fullname" . }}-rabbitmq
  labels:
    {{- include "factorio-tech.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc }}
  password: {{ .Values.rabbitmq.password | b64enc }}
