name: Analyze Bundle Size

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"

      - name: Install
        uses: bahmutov/npm-install@v1
        with:
          working-directory: frontend

      - name: Build & analyze
        run: cd frontend && mkdir -p .next/analyze/master && npm run analyze | tee .next/analyze/output.txt

      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            frontend/.next/analyze/client.html
            frontend/.next/analyze/bundle.json

      - name: Get comment body
        id: get-comment-body
        if: success() && github.event.number
        run: |
          body=$(cat frontend/.next/analyze/bundle-comparison.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: "<!-- GH BOT -->"

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v1.4.4
        if: success() && github.event.number && steps.fc.outputs.comment-id != 0
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
