name: Build and push Docker image
on:
  push:
    branches:
      - main
    paths-ignore:
      - .*/**
      - deploy/**
      - infrastructure/**
      - scripts/**
      - README.md
  pull_request:
    branches:
      - main

env:
  version: "1.0.0-ci${{ github.run_id }}"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push - fbsr-wrapper
        uses: docker/build-push-action@v2
        with:
          context: ./fbsr-wrapper
          file: ./fbsr-wrapper/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/fbsr-wrapper:${{ env.version }}
            ghcr.io/${{ github.repository }}/fbsr-wrapper:ci
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/fbsr-wrapper:ci
          cache-to: type=inline
          labels: |
            org.opencontainers.image.version=${{ env.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ github.ref }}

      - name: Build and push - web
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            version=${{ env.version }}
            build_branch=${{ github.ref }}
            build_sha=${{ github.sha }}
            build_uri=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/web:${{ env.version }}
            ghcr.io/${{ github.repository }}/web:ci
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          labels: |
            org.opencontainers.image.version=${{ env.version }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.ref.name=${{ github.ref }}
